import { readFileSync, readdirSync, copyFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
const {version} = JSON.parse(readFileSync('package.json','utf8'));
const repo = process.env.GITHUB_REPOSITORY || 'taugr/patter';
assert.equal(repo, 'taugr/patter');
const base = process.argv[2] || 'src-tauri/target/release/bundle';
const output = 'release-artifacts';
mkdirSync(output, {recursive:true});
const dmg = readdirSync(`${base}/dmg`).filter(f=>f.endsWith('.dmg'));
assert.equal(dmg.length,1,'Expected exactly one DMG');
const files = [`Patter_${version}_aarch64.dmg`, 'Patter.app.tar.gz', 'Patter.app.tar.gz.sig'];
copyFileSync(`${base}/dmg/${dmg[0]}`,`${output}/${files[0]}`);
for (const name of files.slice(1)) copyFileSync(`${base}/macos/${name}`,`${output}/${name}`);
const signature = readFileSync(`${output}/Patter.app.tar.gz.sig`,'utf8').trim();
assert(signature.length > 100, 'Missing updater signature');
const decoded = Buffer.from(signature,'base64').toString('utf8');
assert(decoded.includes(`version:${version}`),'Signature must bind the release version');
const changesPath = `release-notes/${version}.md`;
const changes = existsSync(changesPath) ? readFileSync(changesPath, 'utf8').trim() : '';
const notes = [`Patter ${version}`, changes, 'Personal preview for Apple Silicon Macs on macOS 15+. No Apple notarization. See the release page for installation instructions and verification limits.'].filter(Boolean).join('\n\n');
writeFileSync(`${output}/latest.json`,JSON.stringify({version,notes,pub_date:new Date().toISOString(),platforms:{'darwin-aarch64':{url:`https://github.com/${repo}/releases/download/v${version}/Patter.app.tar.gz`,signature}}},null,2)+'\n');
files.push('latest.json');
writeFileSync(`${output}/SHA256SUMS`,files.map(name=>`${createHash('sha256').update(readFileSync(`${output}/${name}`)).digest('hex')}  ${name}`).join('\n')+'\n');
writeFileSync(`${output}/release-notes.md`,`${notes}\n\nDownload the DMG, drag Patter to Applications, eject the DMG, then open Patter from Applications. This personal build is ad-hoc signed, without Apple notarization. If macOS blocks it, use the app-specific Open Anyway option in System Settings → Privacy & Security.\n\nUpdates: Settings → Updates → Install and restart. Existing 0.1.0 installations need one manual replacement. Libraries remain local to each Mac. Live capture, Calendar permissions and real model inference still need a supervised test before relying on Patter for important meetings.\n\n[Installation and recovery guide](https://github.com/${repo}/blob/v${version}/INSTALL.md).\n`);
console.log(`Prepared ${files.length + 1} release assets for ${version}`);
